apiVersion: v1
kind: Ingress
metadata:
  labels:
    io.service: enqualify-mapip
  name: enqualify-mapip
  namespace: {{ .Values.namespace }}
spec:
  selector:
    io.service: enqualify-mapip
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: driver
            port:
              number: 80