apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: enqualify-mapip
  name: enqualify-mapip
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: port8080
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    io.service: enqualify-mapip
